apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-app
spec:
  selector:
    matchLabels:
      app: backend-app
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: backend-app
    spec:
      containers:
      - name: backend
        image: {{ .Values.backend.image }}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: {{ .Values.backend.port }}
        env:
        - name: REDIS_URI
          value: redis://redis-svc:6379
